Fixes  mockersf/hocon.rs#41
Instead of the deprecated "failure" crate this PR introduces "thiserror" which can derive Error which are all based upon std::error::Error and thus doesn't introduce a error-handling dependency for library users.

Messages have been mapped from the previous Display-impl to the corresponding macros.

Unfortunately it was not possible to use a transparent-error for std::io::Error because the crate heavily relies on Clone and std::io::Error does not implement Clone.
Hence an additional From<std::io::Error> impl has been added.